services:
  keystonejs:
    image: node:jod-bullseye
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_TELEMETRY_DEBUG=1
    volumes:
      - ./keystonejs:/keystonejs
      - ./eleventy:/eleventy
      - ./vite-frontend:/vite-frontend
      # - /app/node_modules
    working_dir: /keystonejs
    command: sh -c "npm i && npx keystone dev"
    networks:
      - merge_network

  server:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./eleventy/_site:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - keystonejs
    networks:
      - merge_network

networks:
  merge_network:
    driver: bridge
