services:
  # start using: `sudo docker-compose --profile debug up -d`
  keystonejs-debug:
    profiles: [debug]
    image: node:jod-bullseye
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_TELEMETRY_DEBUG=1
    volumes:
      - ./global.ts:/global.ts
      - ./keystonejs-backend:/keystonejs-backend
      - ./vite-frontend:/vite-frontend
    working_dir: /keystonejs-backend
    command: ["sh", "-c", "npm i && npx keystone dev"]
  # start using: `sudo docker-compose --profile production up -d`
  keystonejs-production:
    profiles: [production]
    build: .
    volumes:
      - ./files:/keystonejs-backend/public/files
      - ./images:/keystonejs-backend/public/images
    ports:
      - "3000:3000"
